In [1]:
import pandas as pd

In [2]:
EC = {8: 'ISC/EB',
 9: 'ISC/EB-q',
 4: 'ISC/EB-d1',
 5: 'ISC/EB-d2',
 7: 'EC-im',
 3: 'EC-1',
 2: 'EC-2',
 0: 'EC-3',
 1: 'EC-trypsin 5G1',
 11: 'EC-AA'}

In [3]:
re_EC = {k: i for i, k in enumerate(set(EC.values()))}
re_EC

{'EC-3': 0,
 'ISC/EB': 1,
 'EC-2': 2,
 'ISC/EB-d1': 3,
 'ISC/EB-d2': 4,
 'EC-AA': 5,
 'EC-1': 6,
 'EC-im': 7,
 'ISC/EB-q': 8,
 'EC-trypsin 5G1': 9}

In [4]:
df = pd.read_csv('./seurat.meta_data.csv', index_col=0)
df['celltype'] = df['seurat_clusters'].map(lambda x: EC[x])
df['celltype_id'] = df['celltype'].map(lambda x: re_EC[x])
df

,orig.ident,nCount_RNA,nFeature_RNA,percent.mt,RNA_snn_res.0.9,seurat_clusters,pANN_0.25_0.09_181,DF.classifications_0.25_0.09_181,pANN_0.25_0.09_117,DF.classifications_0.25_0.09_117,integrated_snn_res.0.5,CellName,celltype,celltype_id
AAACCCAAGACTGTTC-1_1,Aedes_midgut,543,158,24.055944,0,1,0.007353,Singlet,NaN,NaN,1,AAACCCAAGACTGTTC-1_1,EC-trypsin 5G1,9
AAACCCACAACACGTT-1_1,Aedes_midgut,5941,626,10.658449,0,3,0.273897,Singlet,NaN,NaN,3,AAACCCACAACACGTT-1_1,EC-1,6
AAACCCACACCTGTCT-1_1,Aedes_midgut,430,180,29.623568,2,5,0.079044,Singlet,NaN,NaN,5,AAACCCACACCTGTCT-1_1,ISC/EB-d2,4
AAACCCACATTGACAC-1_1,Aedes_midgut,15243,1488,6.951480,4,3,0.373162,Singlet,NaN,NaN,3,AAACCCACATTGACAC-1_1,EC-1,6
AAACGAAAGACTTCGT-1_1,Aedes_midgut,4307,592,21.861393,4,2,0.306985,Singlet,NaN,NaN,2,AAACGAAAGACTTCGT-1_1,EC-2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGATCCAGTGGCTC-1_2,Aedes_midgut,807,210,10.099889,1,0,NaN,NaN,0.002857,Singlet,0,TTTGATCCAGTGGCTC-1_2,EC-3,0
TTTGATCTCATGTCAG-1_2,Aedes_midgut,1022,237,14.464883,1,0,NaN,NaN,0.000000,Singlet,0,TTTGATCTCATGTCAG-1_2,EC-3,0
TTTGGAGCAATCGAAA-1_2,Aedes_midgut,1032,247,8.833922,0,2,NaN,NaN,0.002857,Singlet,2,TTTGGAGCAATCGAAA-1_2,EC-2,2
TTTGGAGGTTCCTACC-1_2,Aedes_midgut,1120,275,14.569031,2,7,NaN,NaN,0.054286,Singlet,7,TTTGGAGGTTCCTACC-1_2,EC-im,7
TTTGGTTCAGACATCT-1_2,Aedes_midgut,1095,278,15.704388,0,2,NaN,NaN,0.114286,Singlet,2,TTTGGTTCAGACATCT-1_2,EC-2,2

In [5]:
df.to_csv('./seurat.meta_data.mark_celltype.csv')